### ISSUE TITLE
bello

### ISSUE THREAD

**Issue by Arrowar** [yaserahmady/movies-api#1]
bello ...

**Comment by yaserahmady** [comment]
Ahaha, questa era solo una lezione che ho tenuto per degli studenti. Le mie repo private sono molto in linea con le tue (tantissimi web scraper e downloader) però a differenza tua non sono anonimo su questo profilo!

Mettiamoci in contatto, sono sempre alla ricerca di persone con cui parlare di questi argomenti, soprattutto Italiani. Se hai un canale di comunicazione che preferisci fammi sapere.

**Comment by Ghost6446** [comment]
Canale diretto non proprio, sono attivo solo quando ho due minuti, comunque che progetti avevi ?

**Comment by Arrowar** [comment]
Sei tu questo => https://www.instagram.com/yaser.ahmady/, anonimo perchè non è proprio lecito cioè che pubblico qua

**Comment by yaserahmady** [comment]
> Sei tu questo => https://www.instagram.com/yaser.ahmady/, anonimo perchè non è proprio lecito cioè che pubblico qua

Sono io quello! Se vuoi scrivimi lì e poi cancello la issue.

> Canale diretto non proprio, sono attivo solo quando ho due minuti, comunque che progetti avevi ?

Non intendo che vorrei commissionarti progetti, intendevo solo dire che mi piacerebbe condividere informazioni su web scraping e downloader custom, magari ci sono anche API nascoste utili per servizi italiani, robe così.

**Comment by Ghost6446** [comment]
Si si certo, basta cercare nelle richieste dei siti, in 20 minuti me ne sono fatta una custom per questo sito => https://www.staseraintv.com, perfetto
